#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="aayurvedic")]
public partial class aayurvedicDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Inserttaste(taste instance);
  partial void Updatetaste(taste instance);
  partial void Deletetaste(taste instance);
  partial void Insertvipak(vipak instance);
  partial void Updatevipak(vipak instance);
  partial void Deletevipak(vipak instance);
  partial void Insertfruit(fruit instance);
  partial void Updatefruit(fruit instance);
  partial void Deletefruit(fruit instance);
  partial void Insertsec_question(sec_question instance);
  partial void Updatesec_question(sec_question instance);
  partial void Deletesec_question(sec_question instance);
  partial void Insertreg_temp(reg_temp instance);
  partial void Updatereg_temp(reg_temp instance);
  partial void Deletereg_temp(reg_temp instance);
  #endregion
	
	public aayurvedicDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["aayurvedicConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public aayurvedicDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public aayurvedicDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public aayurvedicDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public aayurvedicDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<suitability> suitabilities
	{
		get
		{
			return this.GetTable<suitability>();
		}
	}
	
	public System.Data.Linq.Table<bodytype> bodytypes
	{
		get
		{
			return this.GetTable<bodytype>();
		}
	}
	
	public System.Data.Linq.Table<timing> timings
	{
		get
		{
			return this.GetTable<timing>();
		}
	}
	
	public System.Data.Linq.Table<category> categories
	{
		get
		{
			return this.GetTable<category>();
		}
	}
	
	public System.Data.Linq.Table<vegetable> vegetables
	{
		get
		{
			return this.GetTable<vegetable>();
		}
	}
	
	public System.Data.Linq.Table<oilfat> oilfats
	{
		get
		{
			return this.GetTable<oilfat>();
		}
	}
	
	public System.Data.Linq.Table<quality> qualities
	{
		get
		{
			return this.GetTable<quality>();
		}
	}
	
	public System.Data.Linq.Table<temperature> temperatures
	{
		get
		{
			return this.GetTable<temperature>();
		}
	}
	
	public System.Data.Linq.Table<season> seasons
	{
		get
		{
			return this.GetTable<season>();
		}
	}
	
	public System.Data.Linq.Table<effect> effects
	{
		get
		{
			return this.GetTable<effect>();
		}
	}
	
	public System.Data.Linq.Table<taste> tastes
	{
		get
		{
			return this.GetTable<taste>();
		}
	}
	
	public System.Data.Linq.Table<vipak> vipaks
	{
		get
		{
			return this.GetTable<vipak>();
		}
	}
	
	public System.Data.Linq.Table<fruit> fruits
	{
		get
		{
			return this.GetTable<fruit>();
		}
	}
	
	public System.Data.Linq.Table<image> images
	{
		get
		{
			return this.GetTable<image>();
		}
	}
	
	public System.Data.Linq.Table<sec_question> sec_questions
	{
		get
		{
			return this.GetTable<sec_question>();
		}
	}
	
	public System.Data.Linq.Table<user_sec_que> user_sec_ques
	{
		get
		{
			return this.GetTable<user_sec_que>();
		}
	}
	
	public System.Data.Linq.Table<user_secque> user_secques
	{
		get
		{
			return this.GetTable<user_secque>();
		}
	}
	
	public System.Data.Linq.Table<reg_temp> reg_temps
	{
		get
		{
			return this.GetTable<reg_temp>();
		}
	}
	
	public System.Data.Linq.Table<reg_final> reg_finals
	{
		get
		{
			return this.GetTable<reg_final>();
		}
	}
	
	public System.Data.Linq.Table<reg_reject> reg_rejects
	{
		get
		{
			return this.GetTable<reg_reject>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.addfruitsample")]
	public int addfruitsample([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> catid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> fruitid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string fruitname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> taste_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> temp_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> vipak_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> quality_id)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), catid, fruitid, fruitname, taste_id, temp_id, vipak_id, quality_id);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.addtosuitability")]
	public int addtosuitability([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> fruitid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> seasonid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> bodytid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string effect)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fruitid, seasonid, bodytid, effect);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_storeimages")]
	public ISingleResult<sp_storeimagesResult> sp_storeimages([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string img_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> img_size, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarBinary(MAX)")] System.Data.Linq.Binary img_data)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, img_name, img_size, img_data);
		return ((ISingleResult<sp_storeimagesResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_reg_temp")]
	public ISingleResult<sp_reg_tempResult> sp_reg_temp([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> userid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string firstname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string lastname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string password)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid, firstname, lastname, email, password);
		return ((ISingleResult<sp_reg_tempResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_secquestions")]
	public int sp_secquestions([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> secq1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> secq2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> secq3, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string ans1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string ans2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string ans3)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, secq1, secq2, secq3, ans1, ans2, ans3);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_updatestatus")]
	public int sp_updatestatus([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string status, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), status, email);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_insertintofinal")]
	public ISingleResult<sp_insertintofinalResult> sp_insertintofinal([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string status)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, status);
		return ((ISingleResult<sp_insertintofinalResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_insertintoreject")]
	public ISingleResult<sp_insertintorejectResult> sp_insertintoreject([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string status)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, status);
		return ((ISingleResult<sp_insertintorejectResult>)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.suitability")]
public partial class suitability
{
	
	private int _fruit_id;
	
	private int _season_id;
	
	private int _bodyt_id;
	
	private string _effect;
	
	private int _timing_id;
	
	public suitability()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fruit_id", DbType="Int NOT NULL")]
	public int fruit_id
	{
		get
		{
			return this._fruit_id;
		}
		set
		{
			if ((this._fruit_id != value))
			{
				this._fruit_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_season_id", DbType="Int NOT NULL")]
	public int season_id
	{
		get
		{
			return this._season_id;
		}
		set
		{
			if ((this._season_id != value))
			{
				this._season_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bodyt_id", DbType="Int NOT NULL")]
	public int bodyt_id
	{
		get
		{
			return this._bodyt_id;
		}
		set
		{
			if ((this._bodyt_id != value))
			{
				this._bodyt_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_effect", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string effect
	{
		get
		{
			return this._effect;
		}
		set
		{
			if ((this._effect != value))
			{
				this._effect = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timing_id", DbType="Int NOT NULL")]
	public int timing_id
	{
		get
		{
			return this._timing_id;
		}
		set
		{
			if ((this._timing_id != value))
			{
				this._timing_id = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bodytype")]
public partial class bodytype
{
	
	private int _bodyt_id;
	
	private string _bodyt_name;
	
	public bodytype()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bodyt_id", DbType="Int NOT NULL")]
	public int bodyt_id
	{
		get
		{
			return this._bodyt_id;
		}
		set
		{
			if ((this._bodyt_id != value))
			{
				this._bodyt_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bodyt_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string bodyt_name
	{
		get
		{
			return this._bodyt_name;
		}
		set
		{
			if ((this._bodyt_name != value))
			{
				this._bodyt_name = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.timing")]
public partial class timing
{
	
	private int _timing_id;
	
	private string _timing_name;
	
	public timing()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timing_id", DbType="Int NOT NULL")]
	public int timing_id
	{
		get
		{
			return this._timing_id;
		}
		set
		{
			if ((this._timing_id != value))
			{
				this._timing_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timing_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string timing_name
	{
		get
		{
			return this._timing_name;
		}
		set
		{
			if ((this._timing_name != value))
			{
				this._timing_name = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.category")]
public partial class category
{
	
	private int _category_id;
	
	private string _category_name;
	
	public category()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_id", DbType="Int NOT NULL")]
	public int category_id
	{
		get
		{
			return this._category_id;
		}
		set
		{
			if ((this._category_id != value))
			{
				this._category_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string category_name
	{
		get
		{
			return this._category_name;
		}
		set
		{
			if ((this._category_name != value))
			{
				this._category_name = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vegetable")]
public partial class vegetable
{
	
	private System.Nullable<int> _veg_id;
	
	private string _veg_name;
	
	private System.Nullable<int> _cat_id;
	
	public vegetable()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_veg_id", DbType="Int")]
	public System.Nullable<int> veg_id
	{
		get
		{
			return this._veg_id;
		}
		set
		{
			if ((this._veg_id != value))
			{
				this._veg_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_veg_name", DbType="NVarChar(100)")]
	public string veg_name
	{
		get
		{
			return this._veg_name;
		}
		set
		{
			if ((this._veg_name != value))
			{
				this._veg_name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_id", DbType="Int")]
	public System.Nullable<int> cat_id
	{
		get
		{
			return this._cat_id;
		}
		set
		{
			if ((this._cat_id != value))
			{
				this._cat_id = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.oilfat")]
public partial class oilfat
{
	
	private System.Nullable<int> _oil_id;
	
	private string _oil_name;
	
	private System.Nullable<int> _cat_id;
	
	public oilfat()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oil_id", DbType="Int")]
	public System.Nullable<int> oil_id
	{
		get
		{
			return this._oil_id;
		}
		set
		{
			if ((this._oil_id != value))
			{
				this._oil_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oil_name", DbType="NVarChar(100)")]
	public string oil_name
	{
		get
		{
			return this._oil_name;
		}
		set
		{
			if ((this._oil_name != value))
			{
				this._oil_name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_id", DbType="Int")]
	public System.Nullable<int> cat_id
	{
		get
		{
			return this._cat_id;
		}
		set
		{
			if ((this._cat_id != value))
			{
				this._cat_id = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.quality")]
public partial class quality
{
	
	private System.Nullable<int> _q_id;
	
	private string _q_name;
	
	public quality()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q_id", DbType="Int")]
	public System.Nullable<int> q_id
	{
		get
		{
			return this._q_id;
		}
		set
		{
			if ((this._q_id != value))
			{
				this._q_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q_name", DbType="NVarChar(50)")]
	public string q_name
	{
		get
		{
			return this._q_name;
		}
		set
		{
			if ((this._q_name != value))
			{
				this._q_name = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.temperature")]
public partial class temperature
{
	
	private int _temp_id;
	
	private string _temp_name;
	
	public temperature()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_temp_id", DbType="Int NOT NULL")]
	public int temp_id
	{
		get
		{
			return this._temp_id;
		}
		set
		{
			if ((this._temp_id != value))
			{
				this._temp_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_temp_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string temp_name
	{
		get
		{
			return this._temp_name;
		}
		set
		{
			if ((this._temp_name != value))
			{
				this._temp_name = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.season")]
public partial class season
{
	
	private int _season_id;
	
	private string _season_name;
	
	public season()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_season_id", DbType="Int NOT NULL")]
	public int season_id
	{
		get
		{
			return this._season_id;
		}
		set
		{
			if ((this._season_id != value))
			{
				this._season_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_season_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string season_name
	{
		get
		{
			return this._season_name;
		}
		set
		{
			if ((this._season_name != value))
			{
				this._season_name = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.effect")]
public partial class effect
{
	
	private int _effect_id;
	
	private string _effect_name;
	
	public effect()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_effect_id", DbType="Int NOT NULL")]
	public int effect_id
	{
		get
		{
			return this._effect_id;
		}
		set
		{
			if ((this._effect_id != value))
			{
				this._effect_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_effect_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string effect_name
	{
		get
		{
			return this._effect_name;
		}
		set
		{
			if ((this._effect_name != value))
			{
				this._effect_name = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.taste")]
public partial class taste : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _taste_id;
	
	private string _taste_name;
	
	private EntitySet<fruit> _fruits;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontaste_idChanging(int value);
    partial void Ontaste_idChanged();
    partial void Ontaste_nameChanging(string value);
    partial void Ontaste_nameChanged();
    #endregion
	
	public taste()
	{
		this._fruits = new EntitySet<fruit>(new Action<fruit>(this.attach_fruits), new Action<fruit>(this.detach_fruits));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taste_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int taste_id
	{
		get
		{
			return this._taste_id;
		}
		set
		{
			if ((this._taste_id != value))
			{
				this.Ontaste_idChanging(value);
				this.SendPropertyChanging();
				this._taste_id = value;
				this.SendPropertyChanged("taste_id");
				this.Ontaste_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taste_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string taste_name
	{
		get
		{
			return this._taste_name;
		}
		set
		{
			if ((this._taste_name != value))
			{
				this.Ontaste_nameChanging(value);
				this.SendPropertyChanging();
				this._taste_name = value;
				this.SendPropertyChanged("taste_name");
				this.Ontaste_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="taste_fruit", Storage="_fruits", ThisKey="taste_id", OtherKey="taste_id")]
	public EntitySet<fruit> fruits
	{
		get
		{
			return this._fruits;
		}
		set
		{
			this._fruits.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_fruits(fruit entity)
	{
		this.SendPropertyChanging();
		entity.taste = this;
	}
	
	private void detach_fruits(fruit entity)
	{
		this.SendPropertyChanging();
		entity.taste = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vipak")]
public partial class vipak : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _vipak_id;
	
	private string _vipak_name;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onvipak_idChanging(int value);
    partial void Onvipak_idChanged();
    partial void Onvipak_nameChanging(string value);
    partial void Onvipak_nameChanged();
    #endregion
	
	public vipak()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vipak_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int vipak_id
	{
		get
		{
			return this._vipak_id;
		}
		set
		{
			if ((this._vipak_id != value))
			{
				this.Onvipak_idChanging(value);
				this.SendPropertyChanging();
				this._vipak_id = value;
				this.SendPropertyChanged("vipak_id");
				this.Onvipak_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vipak_name", DbType="NVarChar(100)")]
	public string vipak_name
	{
		get
		{
			return this._vipak_name;
		}
		set
		{
			if ((this._vipak_name != value))
			{
				this.Onvipak_nameChanging(value);
				this.SendPropertyChanging();
				this._vipak_name = value;
				this.SendPropertyChanged("vipak_name");
				this.Onvipak_nameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.fruit")]
public partial class fruit : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _fruit_id;
	
	private string _fruit_name;
	
	private string _category_id;
	
	private System.Nullable<int> _taste_id;
	
	private System.Nullable<int> _temp_id;
	
	private System.Nullable<int> _vipak_id;
	
	private System.Nullable<int> _q_id;
	
	private EntityRef<taste> _taste;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfruit_idChanging(int value);
    partial void Onfruit_idChanged();
    partial void Onfruit_nameChanging(string value);
    partial void Onfruit_nameChanged();
    partial void Oncategory_idChanging(string value);
    partial void Oncategory_idChanged();
    partial void Ontaste_idChanging(System.Nullable<int> value);
    partial void Ontaste_idChanged();
    partial void Ontemp_idChanging(System.Nullable<int> value);
    partial void Ontemp_idChanged();
    partial void Onvipak_idChanging(System.Nullable<int> value);
    partial void Onvipak_idChanged();
    partial void Onq_idChanging(System.Nullable<int> value);
    partial void Onq_idChanged();
    #endregion
	
	public fruit()
	{
		this._taste = default(EntityRef<taste>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fruit_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int fruit_id
	{
		get
		{
			return this._fruit_id;
		}
		set
		{
			if ((this._fruit_id != value))
			{
				this.Onfruit_idChanging(value);
				this.SendPropertyChanging();
				this._fruit_id = value;
				this.SendPropertyChanged("fruit_id");
				this.Onfruit_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fruit_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string fruit_name
	{
		get
		{
			return this._fruit_name;
		}
		set
		{
			if ((this._fruit_name != value))
			{
				this.Onfruit_nameChanging(value);
				this.SendPropertyChanging();
				this._fruit_name = value;
				this.SendPropertyChanged("fruit_name");
				this.Onfruit_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string category_id
	{
		get
		{
			return this._category_id;
		}
		set
		{
			if ((this._category_id != value))
			{
				this.Oncategory_idChanging(value);
				this.SendPropertyChanging();
				this._category_id = value;
				this.SendPropertyChanged("category_id");
				this.Oncategory_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taste_id", DbType="Int")]
	public System.Nullable<int> taste_id
	{
		get
		{
			return this._taste_id;
		}
		set
		{
			if ((this._taste_id != value))
			{
				if (this._taste.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Ontaste_idChanging(value);
				this.SendPropertyChanging();
				this._taste_id = value;
				this.SendPropertyChanged("taste_id");
				this.Ontaste_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_temp_id", DbType="Int")]
	public System.Nullable<int> temp_id
	{
		get
		{
			return this._temp_id;
		}
		set
		{
			if ((this._temp_id != value))
			{
				this.Ontemp_idChanging(value);
				this.SendPropertyChanging();
				this._temp_id = value;
				this.SendPropertyChanged("temp_id");
				this.Ontemp_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vipak_id", DbType="Int")]
	public System.Nullable<int> vipak_id
	{
		get
		{
			return this._vipak_id;
		}
		set
		{
			if ((this._vipak_id != value))
			{
				this.Onvipak_idChanging(value);
				this.SendPropertyChanging();
				this._vipak_id = value;
				this.SendPropertyChanged("vipak_id");
				this.Onvipak_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q_id", DbType="Int")]
	public System.Nullable<int> q_id
	{
		get
		{
			return this._q_id;
		}
		set
		{
			if ((this._q_id != value))
			{
				this.Onq_idChanging(value);
				this.SendPropertyChanging();
				this._q_id = value;
				this.SendPropertyChanged("q_id");
				this.Onq_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="taste_fruit", Storage="_taste", ThisKey="taste_id", OtherKey="taste_id", IsForeignKey=true)]
	public taste taste
	{
		get
		{
			return this._taste.Entity;
		}
		set
		{
			taste previousValue = this._taste.Entity;
			if (((previousValue != value) 
						|| (this._taste.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._taste.Entity = null;
					previousValue.fruits.Remove(this);
				}
				this._taste.Entity = value;
				if ((value != null))
				{
					value.fruits.Add(this);
					this._taste_id = value.taste_id;
				}
				else
				{
					this._taste_id = default(Nullable<int>);
				}
				this.SendPropertyChanged("taste");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.images")]
public partial class image
{
	
	private string _email;
	
	private int _id;
	
	private string _img_name;
	
	private int _img_size;
	
	private System.Data.Linq.Binary _img_data;
	
	public image()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this._email = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this._id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img_name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
	public string img_name
	{
		get
		{
			return this._img_name;
		}
		set
		{
			if ((this._img_name != value))
			{
				this._img_name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img_size", DbType="Int NOT NULL")]
	public int img_size
	{
		get
		{
			return this._img_size;
		}
		set
		{
			if ((this._img_size != value))
			{
				this._img_size = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img_data", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary img_data
	{
		get
		{
			return this._img_data;
		}
		set
		{
			if ((this._img_data != value))
			{
				this._img_data = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sec_questions")]
public partial class sec_question : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _secq_id;
	
	private string _secq_name;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsecq_idChanging(int value);
    partial void Onsecq_idChanged();
    partial void Onsecq_nameChanging(string value);
    partial void Onsecq_nameChanged();
    #endregion
	
	public sec_question()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_secq_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int secq_id
	{
		get
		{
			return this._secq_id;
		}
		set
		{
			if ((this._secq_id != value))
			{
				this.Onsecq_idChanging(value);
				this.SendPropertyChanging();
				this._secq_id = value;
				this.SendPropertyChanged("secq_id");
				this.Onsecq_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_secq_name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
	public string secq_name
	{
		get
		{
			return this._secq_name;
		}
		set
		{
			if ((this._secq_name != value))
			{
				this.Onsecq_nameChanging(value);
				this.SendPropertyChanging();
				this._secq_name = value;
				this.SendPropertyChanged("secq_name");
				this.Onsecq_nameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.user_sec_ques")]
public partial class user_sec_que
{
	
	private string _email;
	
	private int _q_id;
	
	private string _ans;
	
	public user_sec_que()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this._email = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q_id", DbType="Int NOT NULL")]
	public int q_id
	{
		get
		{
			return this._q_id;
		}
		set
		{
			if ((this._q_id != value))
			{
				this._q_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ans", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
	public string ans
	{
		get
		{
			return this._ans;
		}
		set
		{
			if ((this._ans != value))
			{
				this._ans = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.user_secques")]
public partial class user_secque
{
	
	private string _email;
	
	private int _q_id;
	
	private string _ans;
	
	public user_secque()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this._email = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q_id", DbType="Int NOT NULL")]
	public int q_id
	{
		get
		{
			return this._q_id;
		}
		set
		{
			if ((this._q_id != value))
			{
				this._q_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ans", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string ans
	{
		get
		{
			return this._ans;
		}
		set
		{
			if ((this._ans != value))
			{
				this._ans = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.reg_temp")]
public partial class reg_temp : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _user_id;
	
	private string _firstname;
	
	private string _lastname;
	
	private string _email;
	
	private string _password;
	
	private System.Nullable<int> _status;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void OnfirstnameChanging(string value);
    partial void OnfirstnameChanged();
    partial void OnlastnameChanging(string value);
    partial void OnlastnameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    #endregion
	
	public reg_temp()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int NOT NULL")]
	public int user_id
	{
		get
		{
			return this._user_id;
		}
		set
		{
			if ((this._user_id != value))
			{
				this.Onuser_idChanging(value);
				this.SendPropertyChanging();
				this._user_id = value;
				this.SendPropertyChanged("user_id");
				this.Onuser_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string firstname
	{
		get
		{
			return this._firstname;
		}
		set
		{
			if ((this._firstname != value))
			{
				this.OnfirstnameChanging(value);
				this.SendPropertyChanging();
				this._firstname = value;
				this.SendPropertyChanged("firstname");
				this.OnfirstnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string lastname
	{
		get
		{
			return this._lastname;
		}
		set
		{
			if ((this._lastname != value))
			{
				this.OnlastnameChanging(value);
				this.SendPropertyChanging();
				this._lastname = value;
				this.SendPropertyChanged("lastname");
				this.OnlastnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50)")]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
	public System.Nullable<int> status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.reg_final")]
public partial class reg_final
{
	
	private int _user_id;
	
	private string _firstname;
	
	private string _lastname;
	
	private string _email;
	
	private string _password;
	
	private System.Nullable<int> _status;
	
	public reg_final()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int NOT NULL")]
	public int user_id
	{
		get
		{
			return this._user_id;
		}
		set
		{
			if ((this._user_id != value))
			{
				this._user_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string firstname
	{
		get
		{
			return this._firstname;
		}
		set
		{
			if ((this._firstname != value))
			{
				this._firstname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string lastname
	{
		get
		{
			return this._lastname;
		}
		set
		{
			if ((this._lastname != value))
			{
				this._lastname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this._email = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50)")]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this._password = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
	public System.Nullable<int> status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this._status = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.reg_reject")]
public partial class reg_reject
{
	
	private int _user_id;
	
	private string _firstname;
	
	private string _lastname;
	
	private string _email;
	
	private string _password;
	
	private System.Nullable<int> _status;
	
	public reg_reject()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int NOT NULL")]
	public int user_id
	{
		get
		{
			return this._user_id;
		}
		set
		{
			if ((this._user_id != value))
			{
				this._user_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string firstname
	{
		get
		{
			return this._firstname;
		}
		set
		{
			if ((this._firstname != value))
			{
				this._firstname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string lastname
	{
		get
		{
			return this._lastname;
		}
		set
		{
			if ((this._lastname != value))
			{
				this._lastname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this._email = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50)")]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this._password = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
	public System.Nullable<int> status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this._status = value;
			}
		}
	}
}

public partial class sp_storeimagesResult
{
	
	private System.Nullable<int> _returnvalue;
	
	public sp_storeimagesResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_returnvalue", DbType="Int")]
	public System.Nullable<int> returnvalue
	{
		get
		{
			return this._returnvalue;
		}
		set
		{
			if ((this._returnvalue != value))
			{
				this._returnvalue = value;
			}
		}
	}
}

public partial class sp_reg_tempResult
{
	
	private System.Nullable<int> _returnvalue;
	
	public sp_reg_tempResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_returnvalue", DbType="Int")]
	public System.Nullable<int> returnvalue
	{
		get
		{
			return this._returnvalue;
		}
		set
		{
			if ((this._returnvalue != value))
			{
				this._returnvalue = value;
			}
		}
	}
}

public partial class sp_insertintofinalResult
{
	
	private System.Nullable<int> _returnvalue;
	
	public sp_insertintofinalResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_returnvalue", DbType="Int")]
	public System.Nullable<int> returnvalue
	{
		get
		{
			return this._returnvalue;
		}
		set
		{
			if ((this._returnvalue != value))
			{
				this._returnvalue = value;
			}
		}
	}
}

public partial class sp_insertintorejectResult
{
	
	private System.Nullable<int> _returnvalue;
	
	public sp_insertintorejectResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_returnvalue", DbType="Int")]
	public System.Nullable<int> returnvalue
	{
		get
		{
			return this._returnvalue;
		}
		set
		{
			if ((this._returnvalue != value))
			{
				this._returnvalue = value;
			}
		}
	}
}
#pragma warning restore 1591
